[package]
name = "voyager_explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1", features = [
  "default",
] }
egui = "0.31.1"

egui_extras = { version = "0.31.1", features = [
  "default",
  "all_loaders",
] }

env_logger = { version = "0.11", default-features = false, features = [
  "auto-color",
  "humantime",
] }
hound = "3.5.1"

image = { version = "0.25", features = [
  "jpeg",
  "png",
] }
rfd = "0.15.3"
rodio = "0.20.1"
